# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/docker/2022.1/clean/hdl/projects/u96v2_sbc_base_2022_1/u96v2_sbc_base.srcs/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_pc_8/u96v2_sbc_base_auto_pc_8.xci
# IP: The module: 'u96v2_sbc_base_auto_pc_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docker/2022.1/clean/hdl/projects/u96v2_sbc_base_2022_1/u96v2_sbc_base.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_pc_8/u96v2_sbc_base_auto_pc_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_auto_pc_8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/docker/2022.1/clean/hdl/projects/u96v2_sbc_base_2022_1/u96v2_sbc_base.srcs/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_pc_8/u96v2_sbc_base_auto_pc_8.xci
# IP: The module: 'u96v2_sbc_base_auto_pc_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docker/2022.1/clean/hdl/projects/u96v2_sbc_base_2022_1/u96v2_sbc_base.gen/sources_1/bd/u96v2_sbc_base/ip/u96v2_sbc_base_auto_pc_8/u96v2_sbc_base_auto_pc_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96v2_sbc_base_auto_pc_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
